"""schema_inicial

Revision ID: b14d76a7335b
Revises: 
Create Date: 2026-05-29 12:06:27.472701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.models.base


# revision identifiers, used by Alembic.
revision: str = 'b14d76a7335b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('localizacao', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('humidade_max', sa.Float(), nullable=True),
    sa.Column('fabricante', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('ano_fabrico', sa.Integer(), nullable=True),
    sa.Column('largura_mm', sa.Float(), nullable=True),
    sa.Column('altura_mm', sa.Float(), nullable=True),
    sa.Column('profundidade_mm', sa.Float(), nullable=True),
    sa.Column('volume_l', sa.Float(), nullable=True),
    sa.Column('potencia_kw', sa.Float(), nullable=True),
    sa.Column('ligacao_eletrica', sa.String(length=80), nullable=True),
    sa.Column('corrente_a', sa.Float(), nullable=True),
    sa.Column('voltagem_v', sa.Float(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('peso_max_kg', sa.Float(), nullable=True),
    sa.Column('notas_tecnicas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado_atual', sa.String(length=30), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('criado_em', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('atualizado_em', app.models.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Equipamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Equipamentos_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_Equipamentos_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_Equipamentos_estado_atual'), ['estado_atual'], unique=False)
        batch_op.create_index(batch_op.f('ix_Equipamentos_fabricante'), ['fabricante'], unique=False)
        batch_op.create_index(batch_op.f('ix_Equipamentos_localizacao'), ['localizacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_Equipamentos_modelo'), ['modelo'], unique=False)
        batch_op.create_index(batch_op.f('ix_Equipamentos_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_Equipamentos_numero_serie'), ['numero_serie'], unique=False)
        batch_op.create_index(batch_op.f('ix_Equipamentos_tipo'), ['tipo'], unique=False)
        batch_op.create_index('ix_equipamento_nome_localizacao', ['nome', 'localizacao'], unique=False)

    op.create_table('Utilizadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('iniciais', sa.String(length=10), nullable=True),
    sa.Column('numero_colaborador', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=120), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('forcar_troca_pin', sa.Boolean(), nullable=False),
    sa.Column('criado_em', app.models.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Utilizadores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Utilizadores_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_Utilizadores_cargo'), ['cargo'], unique=False)
        batch_op.create_index(batch_op.f('ix_Utilizadores_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_Utilizadores_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_Utilizadores_numero_colaborador'), ['numero_colaborador'], unique=True)
        batch_op.create_index(batch_op.f('ix_Utilizadores_role'), ['role'], unique=False)
        batch_op.create_index('ix_utilizador_nome_role', ['nome', 'role'], unique=False)

    op.create_table('Avarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_registo', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('resolvida', sa.Boolean(), nullable=False),
    sa.Column('data_resolucao', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('notas_resolucao', sa.Text(), nullable=True),
    sa.Column('custo_reparacao', sa.Float(), nullable=True),
    sa.Column('empresa_externa', sa.String(length=150), nullable=True),
    sa.Column('num_sc_po', sa.String(length=100), nullable=True),
    sa.Column('severidade', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['Equipamentos.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['Utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Avarias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Avarias_data_registo'), ['data_registo'], unique=False)
        batch_op.create_index(batch_op.f('ix_Avarias_data_resolucao'), ['data_resolucao'], unique=False)
        batch_op.create_index(batch_op.f('ix_Avarias_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Avarias_resolvida'), ['resolvida'], unique=False)
        batch_op.create_index(batch_op.f('ix_Avarias_utilizador_id'), ['utilizador_id'], unique=False)
        batch_op.create_index('ix_avaria_equipamento_resolvida', ['equipamento_id', 'resolvida'], unique=False)

    op.create_table('Calibracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('executado_por_id', sa.Integer(), nullable=True),
    sa.Column('data_realizada', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('periodicidade_dias', sa.Integer(), nullable=True),
    sa.Column('proxima_data', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('certificado_url', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', app.models.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['Equipamentos.id'], ),
    sa.ForeignKeyConstraint(['executado_por_id'], ['Utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Calibracoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Calibracoes_data_realizada'), ['data_realizada'], unique=False)
        batch_op.create_index(batch_op.f('ix_Calibracoes_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Calibracoes_executado_por_id'), ['executado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Calibracoes_periodicidade_dias'), ['periodicidade_dias'], unique=False)
        batch_op.create_index(batch_op.f('ix_Calibracoes_proxima_data'), ['proxima_data'], unique=False)
        batch_op.create_index('ix_calibracao_equipamento_data', ['equipamento_id', 'data_realizada'], unique=False)

    op.create_table('DocumentacaoEquipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('carregado_por_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('tipo_documento', sa.String(length=30), nullable=False),
    sa.Column('caminho_ficheiro', sa.String(length=1000), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', app.models.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carregado_por_id'], ['Utilizadores.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['Equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('DocumentacaoEquipamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DocumentacaoEquipamento_carregado_por_id'), ['carregado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_DocumentacaoEquipamento_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_DocumentacaoEquipamento_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_DocumentacaoEquipamento_tipo_documento'), ['tipo_documento'], unique=False)
        batch_op.create_index('ix_documentacao_equipamento_tipo', ['equipamento_id', 'tipo_documento'], unique=False)

    op.create_table('Logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('utilizador_nome', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('criado_em', app.models.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilizador_id'], ['Utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Logs_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_Logs_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_Logs_sucesso'), ['sucesso'], unique=False)
        batch_op.create_index(batch_op.f('ix_Logs_utilizador_id'), ['utilizador_id'], unique=False)
        batch_op.create_index('ix_log_acao_criado', ['acao', 'criado_em'], unique=False)
        batch_op.create_index('ix_log_utilizador_criado', ['utilizador_id', 'criado_em'], unique=False)

    op.create_table('Manutencoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('executado_por_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_realizada', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('periodicidade_dias', sa.Integer(), nullable=True),
    sa.Column('proxima_data', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('criado_em', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('tipo_intervencao', sa.String(length=60), nullable=True),
    sa.Column('custo_eur', sa.Float(), nullable=True),
    sa.Column('referencia_sc_po', sa.String(length=100), nullable=True),
    sa.Column('observacoes_externas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['Equipamentos.id'], ),
    sa.ForeignKeyConstraint(['executado_por_id'], ['Utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Manutencoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Manutencoes_data_realizada'), ['data_realizada'], unique=False)
        batch_op.create_index(batch_op.f('ix_Manutencoes_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Manutencoes_executado_por_id'), ['executado_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Manutencoes_periodicidade_dias'), ['periodicidade_dias'], unique=False)
        batch_op.create_index(batch_op.f('ix_Manutencoes_proxima_data'), ['proxima_data'], unique=False)
        batch_op.create_index('ix_manutencao_equipamento_data', ['equipamento_id', 'data_realizada'], unique=False)

    op.create_table('Reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('projeto', sa.String(length=150), nullable=True),
    sa.Column('metodo', sa.String(length=180), nullable=True),
    sa.Column('data_inicio', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('data_fim', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('duracao_prevista_minutos', sa.Integer(), nullable=True),
    sa.Column('concluido_com_sucesso', sa.Boolean(), nullable=True),
    sa.Column('fim_automatico', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', app.models.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['Equipamentos.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['Utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Reservas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Reservas_concluido_com_sucesso'), ['concluido_com_sucesso'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reservas_data_fim'), ['data_fim'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reservas_data_inicio'), ['data_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reservas_duracao_prevista_minutos'), ['duracao_prevista_minutos'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reservas_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reservas_fim_automatico'), ['fim_automatico'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reservas_metodo'), ['metodo'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reservas_projeto'), ['projeto'], unique=False)
        batch_op.create_index(batch_op.f('ix_Reservas_utilizador_id'), ['utilizador_id'], unique=False)
        batch_op.create_index('ix_reserva_equipamento_periodo', ['equipamento_id', 'data_inicio', 'data_fim'], unique=False)
        batch_op.create_index('ix_reserva_utilizador_periodo', ['utilizador_id', 'data_inicio', 'data_fim'], unique=False)

    op.create_table('SessoesAuth',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('expira_em', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('criado_em', app.models.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilizador_id'], ['Utilizadores.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('SessoesAuth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SessoesAuth_expira_em'), ['expira_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_SessoesAuth_utilizador_id'), ['utilizador_id'], unique=False)
        batch_op.create_index('ix_sessaoauth_utilizador_expira', ['utilizador_id', 'expira_em'], unique=False)

    op.create_table('SessoesUso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=True),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('utilizador', sa.String(length=150), nullable=False),
    sa.Column('inicio', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('fim', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('duracao_prevista_minutos', sa.Integer(), nullable=True),
    sa.Column('fim_automatico', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('termino_forcado', sa.Boolean(), nullable=False),
    sa.Column('valida_para_stats', sa.Boolean(), nullable=False),
    sa.Column('projeto', sa.String(length=150), nullable=True),
    sa.Column('metodo', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['Equipamentos.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['Reservas.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['Utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('SessoesUso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SessoesUso_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_SessoesUso_fim'), ['fim'], unique=False)
        batch_op.create_index(batch_op.f('ix_SessoesUso_fim_automatico'), ['fim_automatico'], unique=False)
        batch_op.create_index(batch_op.f('ix_SessoesUso_inicio'), ['inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_SessoesUso_reserva_id'), ['reserva_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_SessoesUso_termino_forcado'), ['termino_forcado'], unique=False)
        batch_op.create_index(batch_op.f('ix_SessoesUso_utilizador_id'), ['utilizador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_SessoesUso_valida_para_stats'), ['valida_para_stats'], unique=False)
        batch_op.create_index('ix_sessaouso_equipamento_inicio', ['equipamento_id', 'inicio'], unique=False)
        batch_op.create_index('ix_sessaouso_utilizador_inicio', ['utilizador_id', 'inicio'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SessoesUso', schema=None) as batch_op:
        batch_op.drop_index('ix_sessaouso_utilizador_inicio')
        batch_op.drop_index('ix_sessaouso_equipamento_inicio')
        batch_op.drop_index(batch_op.f('ix_SessoesUso_valida_para_stats'))
        batch_op.drop_index(batch_op.f('ix_SessoesUso_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_SessoesUso_termino_forcado'))
        batch_op.drop_index(batch_op.f('ix_SessoesUso_reserva_id'))
        batch_op.drop_index(batch_op.f('ix_SessoesUso_inicio'))
        batch_op.drop_index(batch_op.f('ix_SessoesUso_fim_automatico'))
        batch_op.drop_index(batch_op.f('ix_SessoesUso_fim'))
        batch_op.drop_index(batch_op.f('ix_SessoesUso_equipamento_id'))

    op.drop_table('SessoesUso')
    with op.batch_alter_table('SessoesAuth', schema=None) as batch_op:
        batch_op.drop_index('ix_sessaoauth_utilizador_expira')
        batch_op.drop_index(batch_op.f('ix_SessoesAuth_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_SessoesAuth_expira_em'))

    op.drop_table('SessoesAuth')
    with op.batch_alter_table('Reservas', schema=None) as batch_op:
        batch_op.drop_index('ix_reserva_utilizador_periodo')
        batch_op.drop_index('ix_reserva_equipamento_periodo')
        batch_op.drop_index(batch_op.f('ix_Reservas_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_Reservas_projeto'))
        batch_op.drop_index(batch_op.f('ix_Reservas_metodo'))
        batch_op.drop_index(batch_op.f('ix_Reservas_fim_automatico'))
        batch_op.drop_index(batch_op.f('ix_Reservas_equipamento_id'))
        batch_op.drop_index(batch_op.f('ix_Reservas_duracao_prevista_minutos'))
        batch_op.drop_index(batch_op.f('ix_Reservas_data_inicio'))
        batch_op.drop_index(batch_op.f('ix_Reservas_data_fim'))
        batch_op.drop_index(batch_op.f('ix_Reservas_concluido_com_sucesso'))

    op.drop_table('Reservas')
    with op.batch_alter_table('Manutencoes', schema=None) as batch_op:
        batch_op.drop_index('ix_manutencao_equipamento_data')
        batch_op.drop_index(batch_op.f('ix_Manutencoes_proxima_data'))
        batch_op.drop_index(batch_op.f('ix_Manutencoes_periodicidade_dias'))
        batch_op.drop_index(batch_op.f('ix_Manutencoes_executado_por_id'))
        batch_op.drop_index(batch_op.f('ix_Manutencoes_equipamento_id'))
        batch_op.drop_index(batch_op.f('ix_Manutencoes_data_realizada'))

    op.drop_table('Manutencoes')
    with op.batch_alter_table('Logs', schema=None) as batch_op:
        batch_op.drop_index('ix_log_utilizador_criado')
        batch_op.drop_index('ix_log_acao_criado')
        batch_op.drop_index(batch_op.f('ix_Logs_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_Logs_sucesso'))
        batch_op.drop_index(batch_op.f('ix_Logs_criado_em'))
        batch_op.drop_index(batch_op.f('ix_Logs_acao'))

    op.drop_table('Logs')
    with op.batch_alter_table('DocumentacaoEquipamento', schema=None) as batch_op:
        batch_op.drop_index('ix_documentacao_equipamento_tipo')
        batch_op.drop_index(batch_op.f('ix_DocumentacaoEquipamento_tipo_documento'))
        batch_op.drop_index(batch_op.f('ix_DocumentacaoEquipamento_equipamento_id'))
        batch_op.drop_index(batch_op.f('ix_DocumentacaoEquipamento_criado_em'))
        batch_op.drop_index(batch_op.f('ix_DocumentacaoEquipamento_carregado_por_id'))

    op.drop_table('DocumentacaoEquipamento')
    with op.batch_alter_table('Calibracoes', schema=None) as batch_op:
        batch_op.drop_index('ix_calibracao_equipamento_data')
        batch_op.drop_index(batch_op.f('ix_Calibracoes_proxima_data'))
        batch_op.drop_index(batch_op.f('ix_Calibracoes_periodicidade_dias'))
        batch_op.drop_index(batch_op.f('ix_Calibracoes_executado_por_id'))
        batch_op.drop_index(batch_op.f('ix_Calibracoes_equipamento_id'))
        batch_op.drop_index(batch_op.f('ix_Calibracoes_data_realizada'))

    op.drop_table('Calibracoes')
    with op.batch_alter_table('Avarias', schema=None) as batch_op:
        batch_op.drop_index('ix_avaria_equipamento_resolvida')
        batch_op.drop_index(batch_op.f('ix_Avarias_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_Avarias_resolvida'))
        batch_op.drop_index(batch_op.f('ix_Avarias_equipamento_id'))
        batch_op.drop_index(batch_op.f('ix_Avarias_data_resolucao'))
        batch_op.drop_index(batch_op.f('ix_Avarias_data_registo'))

    op.drop_table('Avarias')
    with op.batch_alter_table('Utilizadores', schema=None) as batch_op:
        batch_op.drop_index('ix_utilizador_nome_role')
        batch_op.drop_index(batch_op.f('ix_Utilizadores_role'))
        batch_op.drop_index(batch_op.f('ix_Utilizadores_numero_colaborador'))
        batch_op.drop_index(batch_op.f('ix_Utilizadores_nome'))
        batch_op.drop_index(batch_op.f('ix_Utilizadores_email'))
        batch_op.drop_index(batch_op.f('ix_Utilizadores_cargo'))
        batch_op.drop_index(batch_op.f('ix_Utilizadores_ativo'))

    op.drop_table('Utilizadores')
    with op.batch_alter_table('Equipamentos', schema=None) as batch_op:
        batch_op.drop_index('ix_equipamento_nome_localizacao')
        batch_op.drop_index(batch_op.f('ix_Equipamentos_tipo'))
        batch_op.drop_index(batch_op.f('ix_Equipamentos_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_Equipamentos_nome'))
        batch_op.drop_index(batch_op.f('ix_Equipamentos_modelo'))
        batch_op.drop_index(batch_op.f('ix_Equipamentos_localizacao'))
        batch_op.drop_index(batch_op.f('ix_Equipamentos_fabricante'))
        batch_op.drop_index(batch_op.f('ix_Equipamentos_estado_atual'))
        batch_op.drop_index(batch_op.f('ix_Equipamentos_criado_em'))
        batch_op.drop_index(batch_op.f('ix_Equipamentos_codigo'))

    op.drop_table('Equipamentos')
    # ### end Alembic commands ###
